name: Deploy Flask APP

on:
  workflow_dispatch:

jobs:
  deploy:
    env: 
       DOCKERHUB_USER: ${{ vars.DOCKERHUB_USERNAME }}
       DOCKER_TAG: latest

    runs-on: self-hosted

    steps:
       - name: checkout code
         uses: actions/checkout@v4

       - name: Docker Login
         run: |
           echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin  

       - name: Deploy With Docker Compose
         run: docker compose up -d 

