name: DevSecOps-End-End-To-Pipeline

on:
  workflow_dispatch:

jobs:
   code-quality:
     uses: ./.github/workflows/Code-quality.yml

   dependency-scan:
     uses: ./.github/workflows/Dependency-scan.yml

   docker-lint:
     uses: ./.github/workflows/Docker-lint.yml

   image-scan:
     needs:
       - code-quality
       - dependency-scan
       - docker-lint
     uses: ./.github/workflows/Image-scan.yml
    
     with:
       dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
       secrets: inherit
    

   deploy:
     needs:
       - image-scan
     uses: ./.github/workflows/Deploy-to-prod-server.yml
     secrets: inherit
