
name: hello workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: say hello to user
        run: echo "hello-doston"

      - name: say hello to username
        run: echo "hello ${{ github.actor }}"

  details:
    runs-on: ubuntu-latest

    steps:
      - name: show version of python and docker
        run: |
          docker --version
          python --version

      - name: show the disk space
        run: |
          echo "disk usage"
          df -h


