name: system Information

on:
  workflow_dispatch:

jobs:
  system-info:
    runs-on: ubuntu-latest

    steps:
      - name: show os
        run: uname -a

      - name: show current directory
        run: pwd

      - name: list files
        run: ls -la

      - name: show disk space
        run: df -h

      - name: show system details
        run: |
         echo "Hostname:"
         hostname

         echo "kernal:"
         uname -r

         echo "Architecture:"
         uname -m

      - name: show CPU information
        run: |
         echo "CPU cores:"
         nproc
        
         echo "CPU Model:"
         lscpu | grep "Model name"
